### ISSUE TITLE
not an issue, just wanting a bit of info regarding the repo

### ISSUE THREAD

**Issue by VaasKahnGrim** [danielga/gm_process#2]
by "asynchronous child processes" is this meaning that this module allows for 1 instance of SRCDS to create another instance of srcds and change various settings such as ip,port,map,vac,ect? or is this referring to some other kind of process?

Looking through the main.cpp I notice functions such as start close and kill which instantly I think of srcds and other programs I use every day, but I am unsure still if thats what I'm seeing or not.

**Comment by danielga** [comment]
You can use this start any program on the host and get access to its in/output. An example would be starting a `git clone`.

**Comment by VaasKahnGrim** [comment]
and the in/outputs of these programs depends on a case by case basis I'm assuming, is there any way to find these?

right now I have the idea for using this as a replacement to running an event server 24/7, starting/stopping an srcds instance and force directing event participants to said server is pretty easy enough. I don't think I'll need to worry too much for in/outputs but for the future I'd like to know where to look if I do need to use that side of the module.

P.S. Thanks for the quick response 👍

**Comment by danielga** [comment]
You need to look at documentation for or run these programs to find out the in/outputs. If it's SRCDS you're after, you're out of luck, VALVe's documentation is very poor.

**Comment by VaasKahnGrim** [comment]
sorry to be reopening this but I'm finally getting to the part where I'm working with this module rather then gathering useful things from github and I'm wondering about these inputs/outputs.

would things such as normal startup parameters and console commands count as inputs? asking to get a better understanding of these inputs/outputs, the valve wiki seems to mainly just be giving stuff related to hammer and entities in maps. nothing really seems to be related to srcds itself. starting the second server seems simple enough so far but having trouble figuring out how to stop it later and figuring out settings for it without having to use a server.cfg file

**Comment by danielga** [comment]
In this example, input is everything that you type into the command line, console commands. So if you write `say hello world\n` into the input stream, you should be seeing the console saying "hello world", hopefully. Startup parameters are not part of this, they're just added after the path of the executable.

**Comment by danielga** [comment]
SRCDS has commands for quitting, so if you manage to pass commands through the input stream, just do it there.

**Comment by VaasKahnGrim** [comment]
perfect, that helps quite a bit thank you. hopefully I can manage to get this thing working flawlessly now :)
